### ISSUE TITLE
Problems with parsing Norwegian mobile numbers starting with "471"

### ISSUE THREAD

**Issue by huyderman** [daddyz/phonelib#100]
There are problems parsing Norwegian phone numbers starting with `471`. I mentioned this in #87, but that issue was closed so I'm opening a new one.

The following spec (RSpec3 syntax) illustrates the problem:

```rb
require 'phonelib'

describe Phonelib do
  describe '.parse' do
    context 'for country NO' do
      cell_numbers = [
        # Control examples
        '95098471', '41044927', '92859554',
        # Numbers starting with 47 without problems
        '47465724', '47944424', '47898180',
        # Numers starting with 471 with problems
        '47144752', '47152183', '47140633'
      ].freeze

      cell_numbers.each do |number|
        context "with phone number #{number}" do
          subject { Phonelib.parse(number, 'NO') }

          it { is_expected.to be_valid }

          describe '.national' do
            subject { Phonelib.parse(number, 'NO').national(false) }
            it { is_expected.to eq number }
          end

          describe '.e164' do
            subject { Phonelib.parse(number, 'NO').e164 }
            it { is_expected.to eq "+47#{number}" }
          end
        end
      end
    end
  end
end
```

As seen below, all the tests pass for the control numbers and those just starting with `47`, but not those starting with `471` apparently. 
```
rspec spec/phonelib_no_spec.rb 
..................FFFFFFFFF

Failures:

  1) Phonelib.parse for country NO with phone number 47144752 should be valid
     Failure/Error: it { is_expected.to be_valid }
       expected `#<Phonelib::Phone:0x00000002e56f58 @original="47144752", @extension="", @sanitized="47144752", @data=...})(\\d{4})", :format=>"$1 $2 $3"}, :valid=>[], :possible=>[:toll_free]}}, @national_number="144752">.valid?` to return true, got false
     # ./spec/phonelib_no_spec.rb:19:in `block (6 levels) in <top (required)>'

  2) Phonelib.parse for country NO with phone number 47144752 .national should eq "47144752"
     Failure/Error: it { is_expected.to eq number }

       expected: "47144752"
            got: "144752"

       (compared using ==)
     # ./spec/phonelib_no_spec.rb:23:in `block (7 levels) in <top (required)>'

  3) Phonelib.parse for country NO with phone number 47144752 .e164 should eq "+4747144752"
     Failure/Error: it { is_expected.to eq "+47#{number}" }

       expected: "+4747144752"
            got: "+47144752"

       (compared using ==)
     # ./spec/phonelib_no_spec.rb:28:in `block (7 levels) in <top (required)>'

  4) Phonelib.parse for country NO with phone number 47152183 should be valid
     Failure/Error: it { is_expected.to be_valid }
       expected `#<Phonelib::Phone:0x00000002de8620 @original="47152183", @extension="", @sanitized="47152183", @data=...})(\\d{4})", :format=>"$1 $2 $3"}, :valid=>[], :possible=>[:toll_free]}}, @national_number="152183">.valid?` to return true, got false
     # ./spec/phonelib_no_spec.rb:19:in `block (6 levels) in <top (required)>'

  5) Phonelib.parse for country NO with phone number 47152183 .national should eq "47152183"
     Failure/Error: it { is_expected.to eq number }

       expected: "47152183"
            got: "152183"

       (compared using ==)
     # ./spec/phonelib_no_spec.rb:23:in `block (7 levels) in <top (required)>'

  6) Phonelib.parse for country NO with phone number 47152183 .e164 should eq "+4747152183"
     Failure/Error: it { is_expected.to eq "+47#{number}" }

       expected: "+4747152183"
            got: "+47152183"

       (compared using ==)
     # ./spec/phonelib_no_spec.rb:28:in `block (7 levels) in <top (required)>'

  7) Phonelib.parse for country NO with phone number 47140633 should be valid
     Failure/Error: it { is_expected.to be_valid }
       expected `#<Phonelib::Phone:0x00000002ddb7b8 @original="47140633", @extension="", @sanitized="47140633", @data=...})(\\d{4})", :format=>"$1 $2 $3"}, :valid=>[], :possible=>[:toll_free]}}, @national_number="140633">.valid?` to return true, got false
     # ./spec/phonelib_no_spec.rb:19:in `block (6 levels) in <top (required)>'

  8) Phonelib.parse for country NO with phone number 47140633 .national should eq "47140633"
     Failure/Error: it { is_expected.to eq number }

       expected: "47140633"
            got: "140633"

       (compared using ==)
     # ./spec/phonelib_no_spec.rb:23:in `block (7 levels) in <top (required)>'

  9) Phonelib.parse for country NO with phone number 47140633 .e164 should eq "+4747140633"
     Failure/Error: it { is_expected.to eq "+47#{number}" }

       expected: "+4747140633"
            got: "+47140633"

       (compared using ==)
     # ./spec/phonelib_no_spec.rb:28:in `block (7 levels) in <top (required)>'

Finished in 0.03437 seconds (files took 0.09161 seconds to load)
27 examples, 9 failures

Failed examples:

rspec ./spec/phonelib_no_spec.rb[1:1:1:7:1] # Phonelib.parse for country NO with phone number 47144752 should be valid
rspec ./spec/phonelib_no_spec.rb[1:1:1:7:2:1] # Phonelib.parse for country NO with phone number 47144752 .national should eq "47144752"
rspec ./spec/phonelib_no_spec.rb[1:1:1:7:3:1] # Phonelib.parse for country NO with phone number 47144752 .e164 should eq "+4747144752"
rspec ./spec/phonelib_no_spec.rb[1:1:1:8:1] # Phonelib.parse for country NO with phone number 47152183 should be valid
rspec ./spec/phonelib_no_spec.rb[1:1:1:8:2:1] # Phonelib.parse for country NO with phone number 47152183 .national should eq "47152183"
rspec ./spec/phonelib_no_spec.rb[1:1:1:8:3:1] # Phonelib.parse for country NO with phone number 47152183 .e164 should eq "+4747152183"
rspec ./spec/phonelib_no_spec.rb[1:1:1:9:1] # Phonelib.parse for country NO with phone number 47140633 should be valid
rspec ./spec/phonelib_no_spec.rb[1:1:1:9:2:1] # Phonelib.parse for country NO with phone number 47140633 .national should eq "47140633"
rspec ./spec/phonelib_no_spec.rb[1:1:1:9:3:1] # Phonelib.parse for country NO with phone number 47140633 .e164 should eq "+4747140633"
```

**Comment by daddyz** [comment]
@huyderman Check with master please, I did small change and updated data. Your tests should pass now, added them to my specs

**Comment by huyderman** [comment]
Looks good :+1:

**Comment by daddyz** [comment]
@huyderman great
