### ISSUE TITLE
Handling cell numbers of Cuba which start with 53XXXXXX when not prefixed by +53

### ISSUE THREAD

**Issue by pedroleon** [daddyz/phonelib#164]
Hi!

We have found an issue about parsing cuban cell phone numbers which starts with 53 (same as international prefix for Cuba). Those numbers are valid if have the international number prefix, but not without it.

**SPEC**
   
```
 context "with valid cuban phone number" do
      it "should be true" do
        expect(Phonelib.parse('53317131', 'CU').valid?).to be true
      end
    end

context "with a valid cuban phone with country code" do
  it "should add international prefix to international phone number" do
    expect(Phonelib.parse('53317131', 'CU').international(false)).to eq('5353317131')
  end
end
```

But the results of the specs does not meet the requirements:

```
Failures:

  1) Phonelib.valid? with valid cuban phone number should be true
     Failure/Error: expect(Phonelib.parse('53317131', 'CU').valid?).to be true

       expected #<TrueClass:20> => true
            got #<FalseClass:0> => false

       Compared using equal?, which compares object identity,
       but expected and actual are not the same object. Use
       `expect(actual).to eq(expected)` if you don't care about
       object identity in this example.
     # ./spec/phonelib_spec.rb:56:in `block (4 levels) in <top (required)>'

  2) Phonelib.valid? with a valid cuban phone with country code should add international prefix to international phone number
     Failure/Error: expect(Phonelib.parse('53317131', 'CU').international(false)).to eq('5353317131')

       expected: "5353317131"
            got: "+53317131"

       (compared using ==)
     # ./spec/phonelib_spec.rb:62:in `block (4 levels) in <top (required)>'

Finished in 1.11 seconds
184 examples, 2 failures

Failed examples:

rspec ./spec/phonelib_spec.rb:55 # Phonelib.valid? with valid cuban phone number should be true
rspec ./spec/phonelib_spec.rb:61 # Phonelib.valid? with a valid cuban phone with country code should add international prefix to international phone number
```

I hope this is useful information.
Thank you for your great work!

**Comment by daddyz** [comment]
@pedroleon Hi, check version 0.6.35. It works as expected there. Thanks for reporting.
