### ISSUE TITLE
Crash with some phone numbers

### ISSUE THREAD

**Issue by kidlab** [daddyz/phonelib#55]
I got some trouble when initializing some phone numbers like this `119660086441`:
```ruby
phone = Phonelib::Phone.new("119660086441")
```

```
NoMethodError: undefined method `match' for nil:NilClass
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:211:in `block in get_number_format'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:209:in `each'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:209:in `find'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:209:in `get_number_format'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:149:in `get_national_and_data'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:69:in `parse_single_country'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:81:in `block in detect_and_parse'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:80:in `each'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:80:in `detect_and_parse'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone_analyzer.rb:26:in `analyze'
~/.rvm/gems/ruby-2.0.0-p643/gems/phonelib-0.4.7/lib/phonelib/phone.rb:24:in `initialize'
```

**Comment by daddyz** [comment]
@kidlab, Hi, I made a fix, please check against master branch. Thanks

**Comment by kidlab** [comment]
Thanks @daddyz I have tried with master branch, it does not crash anymore :+1:
