### ISSUE TITLE
Trying to validate ";" as phone number return an error instead of an exception (or other output)

### ISSUE THREAD

**Issue by gamba** [daddyz/phonelib#83]
```
Phonelib.parse(";")
```

returns NoMethodError insted of an exception (or other output)

```
NoMethodError: undefined method `empty?' for nil:NilClass
	from .../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/phonelib-0.6.2/lib/phonelib/phone.rb:26:in `initialize'
	from .../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/phonelib-0.6.2/lib/phonelib/core.rb:241:in `new'
	from .../.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/phonelib-0.6.2/lib/phonelib/core.rb:241:in `parse'
```

**Comment by daddyz** [comment]
@gamba Fixed the issue, thanks for reporting. Check against master or new version.
